  UI-repeat-bug[m
  add-classes-component[m
  add-course-dropdown[m
* [32mapi-docs[m
  badges-ui[m
  card-spacing[m
  consolidate-pages[m
  course-card-revamp[m
  course-to-user[m
  course-ui-sync[m
  delete-course[m
  design-doc[m
  details-view[m
  eval-prereqs[m
  frontend-connection[m
  implement-add-course[m
  implement-is-course-added[m
  info-dialog[m
  info-page[m
  main[m
  new-api-routes[m
  new-spec-doc[m
  no-duplicate-class-cards[m
  planner-page[m
  planner-widgets[m
  post-picker-ui[m
  spec-doc-update[m
  sprint-1-end-ui-tweak[m
  sprint-1-pytest-fixup[m
  sprint-1-wip[m
  sprint-2-wip[m
  stage[m
  story-1[m
  update-ui[m
